#!/usr/bin/env python3
"""One-command setup for claude-hive.

    python3 scripts/setup.py            # set everything up
    python3 scripts/setup.py --check    # diagnose, change nothing

Brings up the local Matrix homeserver and wires this machine's Claude Code
into it. Every step is idempotent, so re-running after a partial failure (or
after an upgrade) is the supported way to repair an installation.

Steps, in order:
 1. preflight      python, uv, docker
 2. homeserver     ~/.claude-hive/matrix/continuwuity.toml + a random
                   registration token, generated once and never overwritten
 3. container      start (or create) hive-matrix, then wait for the client
                   API to actually answer — "Up" is not proof
 4. observer       your own Matrix account, so you can watch the agents talk
 5. claude         delivery hooks, skills, and HIVE_HUMAN_MXID in
                   ~/.claude/settings.json
 6. mcp            register the claude-hive MCP server with Claude Code

Stdlib-only and dependency-free on purpose: this runs from a fresh clone,
before `uv sync` has been near it.
"""
from __future__ import annotations

import argparse
import json
import os
import re
import secrets
import shutil
import socket
import subprocess
import sys
import time
import urllib.error
import urllib.request
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import install_claude  # noqa: E402
import install_codex  # noqa: E402

REPO_ROOT = Path(__file__).resolve().parents[1]
MATRIX_DIR = Path(os.environ.get("CLAUDE_HIVE_MATRIX_DIR",
                                 Path.home() / ".claude-hive" / "matrix"))
CONFIG_FILE = MATRIX_DIR / "continuwuity.toml"
TOKEN_FILE = MATRIX_DIR / "registration_token"

CONTAINER = "hive-matrix"
VOLUME = "hive-matrix-data"
IMAGE = "ghcr.io/continuwuity/continuwuity:latest"
ELEMENT_CONTAINER = "hive-element"
ELEMENT_IMAGE = "vectorim/element-web:latest"
ELEMENT_PORT = 8009

SERVER_NAME = os.environ.get("HIVE_MATRIX_SERVER_NAME", "hive.local")
MATRIX_URL = os.environ.get("HIVE_MATRIX_URL", "http://127.0.0.1:8008")
MATRIX_PORT = 8008

CONFIG_TEMPLATE = """\
# Generated by claude-hive scripts/setup.py. Safe to edit; setup never
# overwrites an existing file.
[global]
server_name = "{server_name}"
address = "0.0.0.0"
port = {port}
database_path = "/var/lib/continuwuity"
allow_registration = true
registration_token = "{token}"
# One homeserver is one hive: no federation, no outside traffic.
allow_federation = false
new_user_displayname_suffix = ""
allow_encryption = false
"""

OK, WARN, FAIL = "ok", "warn", "fail"
_MARK = {OK: "✓", WARN: "!", FAIL: "✗"}
_failed = False
_warned = False


def say(state: str, step: str, detail: str = "") -> None:
    global _failed, _warned
    if state == FAIL:
        _failed = True
    if state == WARN:
        _warned = True
    print(f" {_MARK[state]} {step:<12} {detail}".rstrip())


def die(message: str) -> None:
    print(f"\n{message}", file=sys.stderr)
    sys.exit(1)


def run(*args: str, check: bool = True) -> subprocess.CompletedProcess:
    return subprocess.run(args, capture_output=True, text=True, check=check)


def docker(*args: str, check: bool = True) -> subprocess.CompletedProcess:
    return run("docker", *args, check=check)


def container_state(name: str) -> str | None:
    """"running", "exited", ... or None when no such container exists."""
    proc = docker("inspect", "-f", "{{.State.Status}}", name, check=False)
    return proc.stdout.strip() if proc.returncode == 0 else None


def homeserver_responds(url: str = MATRIX_URL, timeout: float = 3.0) -> bool:
    try:
        with urllib.request.urlopen(f"{url}/_matrix/client/versions",
                                    timeout=timeout) as r:
            return r.status == 200
    except (OSError, urllib.error.HTTPError):
        return False


def port_is_free(port: int) -> bool:
    with socket.socket() as s:
        s.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
        try:
            s.bind(("127.0.0.1", port))
            return True
        except OSError:
            return False


def matrix_post(path: str, body: dict, token: str | None = None) -> tuple[int, dict]:
    req = urllib.request.Request(
        f"{MATRIX_URL}/_matrix/client/v3{path}",
        data=json.dumps(body).encode(),
        headers={"Content-Type": "application/json",
                 **({"Authorization": f"Bearer {token}"} if token else {})},
        method="POST")
    try:
        with urllib.request.urlopen(req, timeout=10) as r:
            return r.status, json.loads(r.read())
    except urllib.error.HTTPError as exc:
        try:
            return exc.code, json.loads(exc.read())
        except ValueError:
            return exc.code, {}


def step_preflight(check_only: bool) -> None:
    if sys.version_info < (3, 11):  # noqa: UP036
        say(FAIL, "python", f"{sys.version.split()[0]} — claude-hive needs 3.11+")
    else:
        say(OK, "python", sys.version.split()[0])

    if shutil.which("uv"):
        say(OK, "uv", shutil.which("uv"))
    else:
        say(FAIL, "uv", "not found — install from https://docs.astral.sh/uv/")

    if not shutil.which("docker"):
        say(FAIL, "docker", "not found — needed to run the Matrix homeserver")
        return
    proc = docker("info", check=False)
    if proc.returncode != 0:
        say(FAIL, "docker", "daemon not reachable (is it running? are you in the docker group?)")
    else:
        say(OK, "docker", "daemon reachable")

    if shutil.which("claude"):
        say(OK, "claude", shutil.which("claude"))
    else:
        say(WARN, "claude", "CLI not found — MCP registration will be skipped")


def step_homeserver(check_only: bool) -> None:
    if CONFIG_FILE.exists() and TOKEN_FILE.exists():
        say(OK, "config", f"{CONFIG_FILE} (existing, left alone)")
        return
    if check_only:
        say(FAIL, "config", f"{CONFIG_FILE} missing — run setup without --check")
        return
    MATRIX_DIR.mkdir(parents=True, exist_ok=True)
    token = TOKEN_FILE.read_text().strip() if TOKEN_FILE.exists() else secrets.token_hex(16)
    TOKEN_FILE.write_text(token + "\n")
    TOKEN_FILE.chmod(0o600)
    if not CONFIG_FILE.exists():
        CONFIG_FILE.write_text(CONFIG_TEMPLATE.format(
            server_name=SERVER_NAME, port=MATRIX_PORT, token=token))
        CONFIG_FILE.chmod(0o600)
    say(OK, "config", f"generated {CONFIG_FILE} (server_name={SERVER_NAME})")


def _create_container() -> None:
    docker("run", "-d",
           "--name", CONTAINER,
           "--restart", "unless-stopped",
           "-p", f"127.0.0.1:{MATRIX_PORT}:{MATRIX_PORT}",
           "-v", f"{CONFIG_FILE}:/etc/continuwuity/continuwuity.toml",
           "-v", f"{VOLUME}:/var/lib/continuwuity",
           "-e", "CONTINUWUITY_CONFIG=/etc/continuwuity/continuwuity.toml",
           IMAGE)


def _wait_for_homeserver(seconds: int = 60) -> bool:
    deadline = time.time() + seconds
    while time.time() < deadline:
        if homeserver_responds():
            return True
        time.sleep(1.0)
    return False


def step_container(check_only: bool) -> None:
    if not shutil.which("docker"):
        return
    state = container_state(CONTAINER)
    if check_only:
        if homeserver_responds():
            say(OK, "homeserver", f"{MATRIX_URL} answering")
        elif state is None:
            say(FAIL, "homeserver", f"no {CONTAINER} container — run setup without --check")
        else:
            say(FAIL, "homeserver", f"container is '{state}' but {MATRIX_URL} is not answering "
                                    f"(try: docker logs {CONTAINER})")
        return

    if state is None:
        if not port_is_free(MATRIX_PORT) and not homeserver_responds():
            say(FAIL, "homeserver", f"port {MATRIX_PORT} is taken by something that is not "
                                    f"a Matrix homeserver")
            return
        say(OK, "homeserver", f"creating {CONTAINER} from {IMAGE}…")
        _create_container()
    elif state != "running":
        docker("start", CONTAINER)

    if _wait_for_homeserver():
        say(OK, "homeserver", f"{MATRIX_URL} answering")
    else:
        say(FAIL, "homeserver", f"container up but {MATRIX_URL} never answered — "
                                f"check `docker logs {CONTAINER}`")


def observer_mxid() -> str | None:
    """The configured observer, from the env or Claude's settings."""
    env = os.environ.get("HIVE_HUMAN_MXID")
    if env is not None:
        return env or None
    try:
        settings = json.loads(install_claude.SETTINGS.read_text())
    except (OSError, ValueError):
        return None
    return (settings.get("env") or {}).get("HIVE_HUMAN_MXID") or None


AGENT_ACCOUNT = re.compile(r"^(a|s)[0-9a-f]{8}")
LEGACY_SESSION_ACCOUNT = re.compile(r"^s[0-9a-f]+$")


def existing_observer_localpart() -> str | None:
    """An observer account this machine already has credentials for — so an
    upgrade keeps watching as whoever it was watching as before."""
    try:
        files = sorted((MATRIX_DIR / "accounts").glob("*.json"))
    except OSError:
        return None
    for f in files:
        if not AGENT_ACCOUNT.match(f.stem) and not f.stem.startswith("lookout-"):
            return f.stem
    return None


def _default_observer_localpart() -> str:
    found = existing_observer_localpart()
    if found:
        return found
    raw = os.environ.get("USER") or os.environ.get("USERNAME") or "operator"
    return re.sub(r"[^a-z0-9._=-]", "", raw.lower()) or "operator"


def _register_observer(localpart: str) -> tuple[str, str] | None:
    """Register (or recognise) the observer account; returns (mxid, password).
    None when the account exists but this machine has no stored password."""
    account_file = MATRIX_DIR / "accounts" / f"{localpart}.json"
    if account_file.exists():
        stored = json.loads(account_file.read_text())
        return stored["user_id"], stored["password"]

    password = secrets.token_urlsafe(18)
    body = {"username": localpart, "password": password,
            "initial_device_display_name": "claude-hive observer"}
    status, data = matrix_post("/register", body)
    if status == 401 and "session" in data:
        body["auth"] = {"type": "m.login.registration_token",
                        "token": TOKEN_FILE.read_text().strip(),
                        "session": data["session"]}
        status, data = matrix_post("/register", body)
    if status != 200 or "user_id" not in data:
        if data.get("errcode") == "M_USER_IN_USE":
            return None
        die(f"observer registration failed: {data.get('errcode')} {data.get('error')}")

    account_file.parent.mkdir(parents=True, exist_ok=True)
    account_file.write_text(json.dumps({"user_id": data["user_id"], "password": password}))
    account_file.chmod(0o600)
    return data["user_id"], password


def step_observer(check_only: bool, requested: str | None, assume_yes: bool) -> str | None:
    existing = observer_mxid()
    if check_only:
        if existing:
            stored = MATRIX_DIR / "accounts" / f"{existing.split(':')[0].lstrip('@')}.json"
            note = "" if stored.exists() else " (no stored password — invites need manual accept)"
            say(OK, "observer", existing + note)
        elif existing_observer_localpart():
            say(WARN, "observer", f"@{existing_observer_localpart()}:{SERVER_NAME} exists but "
                                  f"HIVE_HUMAN_MXID is unset — run setup to wire it up")
        else:
            say(WARN, "observer", "none configured — agent rooms invite nobody")
        return existing
    if existing and not requested:
        say(OK, "observer", f"{existing} (existing)")
        return existing
    if not homeserver_responds():
        say(FAIL, "observer", "skipped — homeserver is not answering")
        return existing

    localpart = requested or _default_observer_localpart()
    if not requested and not assume_yes and sys.stdin.isatty():
        answer = input(f"   Matrix username to watch the hive as [{localpart}]: ").strip()
        localpart = re.sub(r"[^a-z0-9._=-]", "", answer.lower()) or localpart

    result = _register_observer(localpart)
    if result is None:
        say(WARN, "observer", f"@{localpart}:{SERVER_NAME} already exists on the homeserver "
                              f"but this machine has no password for it — invites will need "
                              f"a manual accept in your Matrix client")
        return f"@{localpart}:{SERVER_NAME}"
    mxid, password = result
    say(OK, "observer", f"{mxid} (password in {MATRIX_DIR}/accounts/{localpart}.json)")
    return mxid


def legacy_artifacts() -> tuple[list[Path], Path | None]:
    """Leftovers from before agents became Matrix accounts: per-session
    account credentials and the dm-rooms.json pair cache. Nothing reads them
    any more; the rooms and accounts still exist on the homeserver."""
    try:
        stale = sorted(f for f in (MATRIX_DIR / "accounts").glob("s*.json")
                       if LEGACY_SESSION_ACCOUNT.match(f.stem))
    except OSError:
        stale = []
    dm_rooms = MATRIX_DIR / "dm-rooms.json"
    return stale, dm_rooms if dm_rooms.exists() else None


def step_legacy(check_only: bool, prune: bool) -> None:
    stale, dm_rooms = legacy_artifacts()
    count = len(stale) + (1 if dm_rooms else 0)
    if not count:
        return
    if not prune:
        say(WARN, "legacy", f"{len(stale)} pre-agent-account session credential file(s)"
                            f"{' + dm-rooms.json' if dm_rooms else ''} in {MATRIX_DIR} — "
                            f"unused; remove with --prune-legacy")
        return
    if check_only:
        return
    for f in stale:
        f.unlink(missing_ok=True)
    if dm_rooms:
        dm_rooms.unlink(missing_ok=True)
    say(OK, "legacy", f"pruned {count} unused file(s)")


def step_claude(check_only: bool, mxid: str | None) -> None:
    if check_only:
        installed = install_claude.hooks_installed()
        say(OK if installed else FAIL, "hooks",
            "installed in ~/.claude/settings.json" if installed
            else "missing — run setup without --check")
        linked = install_claude.skills_linked()
        say(OK if linked else FAIL, "skills",
            f"{linked} linked into ~/.claude/skills" if linked else "not linked")
        return
    say(OK, "hooks", "installed" if install_claude.install_hooks() else "already present")
    linked = install_claude.install_skills()
    say(OK, "skills", f"linked {', '.join(linked)}" if linked else "already current")
    if mxid and install_claude.set_env("HIVE_HUMAN_MXID", mxid):
        say(OK, "settings", f"HIVE_HUMAN_MXID={mxid}")


def step_mcp(check_only: bool) -> None:
    status = install_claude.mcp_status()
    if status == "registered":
        say(OK, "mcp", "claude-hive registered with Claude Code")
        return
    if check_only or not shutil.which("claude"):
        say(FAIL, "mcp", "not registered — run:\n" + install_claude.mcp_add_hint())
        return
    proc = run(*install_claude.mcp_add_command(), check=False)
    if proc.returncode == 0:
        say(OK, "mcp", "registered claude-hive with Claude Code")
    else:
        say(FAIL, "mcp", "registration failed — run it yourself:\n"
                         + install_claude.mcp_add_hint()
                         + f"\n   ({proc.stderr.strip() or proc.stdout.strip()})")


def step_element(check_only: bool) -> None:
    state = container_state(ELEMENT_CONTAINER)
    url = f"http://127.0.0.1:{ELEMENT_PORT}"
    if check_only:
        say(OK if state == "running" else WARN, "element",
            f"{url}" if state == "running" else "not running")
        return
    if state is None:
        config = MATRIX_DIR / "element-config.json"
        config.write_text(json.dumps({
            "default_server_config": {
                "m.homeserver": {"base_url": MATRIX_URL, "server_name": SERVER_NAME}},
            "disable_guests": True,
        }, indent=2) + "\n")
        docker("run", "-d",
               "--name", ELEMENT_CONTAINER,
               "--restart", "unless-stopped",
               "-p", f"127.0.0.1:{ELEMENT_PORT}:80",
               "-v", f"{config}:/app/config.json:ro",
               ELEMENT_IMAGE)
    elif state != "running":
        docker("start", ELEMENT_CONTAINER)
    say(OK, "element", f"{url} — log in as the observer to watch the hive")


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Set up claude-hive: homeserver, observer account, Claude Code wiring.")
    parser.add_argument("--check", action="store_true",
                        help="diagnose an existing installation; change nothing")
    parser.add_argument("--observer", metavar="NAME",
                        help="Matrix username to watch the hive as (default: $USER)")
    parser.add_argument("--with-element", action="store_true",
                        help="also run the Element web client at "
                             f"http://127.0.0.1:{ELEMENT_PORT}")
    parser.add_argument("--codex", action="store_true",
                        help="also wire Codex into this project (.codex/hooks.json)")
    parser.add_argument("--prune-legacy", action="store_true",
                        help="delete unused pre-agent-account credential files")
    parser.add_argument("--yes", "-y", action="store_true",
                        help="take defaults, never prompt")
    args = parser.parse_args()

    print(f"\nclaude-hive {'check' if args.check else 'setup'} — {REPO_ROOT}\n")
    step_preflight(args.check)
    if _failed and not args.check:
        die("Fix the failures above, then run setup again.")

    step_homeserver(args.check)
    step_container(args.check)
    mxid = step_observer(args.check, args.observer, args.yes)
    step_legacy(args.check, args.prune_legacy)
    step_claude(args.check, mxid)
    step_mcp(args.check)
    if args.with_element or container_state(ELEMENT_CONTAINER):
        step_element(args.check)
    if args.codex and not args.check:
        install_codex.install_skills_link(REPO_ROOT)
        say(OK, "codex", install_codex.install_hooks(REPO_ROOT)
            + f"; register once with: codex mcp add claude-hive -- "
              f"uv run --project {REPO_ROOT} claude-hive-server")

    if _failed:
        print("\nSomething above needs attention. Re-run this script after fixing it "
              "— every step is idempotent.\n")
        return 1
    if args.check:
        print("\nThe hive is usable; see the ! lines above.\n" if _warned
              else "\nEverything checks out.\n")
        return 0
    print("\nDone. Restart Claude Code (or /mcp reconnect), then run /hive-connect "
          "in each session you want on the hive.\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
